name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - thumbv7em-none-eabi
          - x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2

      - name: Install build dependencies
        shell: bash
        run: |
          env && pwd && sudo apt-get update -y -qq && sudo apt-get install -y -qq llvm libc6-dev-i386 libclang-dev

      - uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: "9-2020-q2"

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          components: llvm-tools-preview

      - name: Build
        run: cargo build --release --verbose --target ${{ matrix.target }}

      - name: Build examples
        run: cargo build --verbose --examples --target ${{ matrix.target }}
        if: matrix.target != 'x86_64-unknown-linux-gnu'

